services:
  app:
    build:
      target: dev
    environment:
      RAILS_ENV: development
    image: localhost:5001/organize-app-dev
    volumes:
      - ./app:/usr/src/app
  certs:
    environment:
      SELF_SIGN: true
    restart: "no"
  web:
    build:
      target: dev
    image: localhost:5001/organize-web-dev
