services:
  api:
    build:
      target: dev
    image: localhost:5001/organize-api-dev
    volumes:
      - ./api:/rails
  certs:
    environment:
      SELF_SIGN: true
    restart: "no"
  site:
    build:
      target: dev
    image: localhost:5001/organize-site-dev
    volumes:
      - ./site:/rails
  web:
    build:
      target: dev
    ports:
      - "8080:80"
    image: localhost:5001/organize-web-dev
