services:
  app:
    depends_on:
      - db
    environment:
      ORGANIZE_DATABASE_PASSWORD: ${ORGANIZE_DATABASE_PASSWORD:?err}
      ORGANIZE_DATABASE_USER: postgres
      ORGANIZE_DATABASE_HOST: db
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY:?err}
    image: localhost:5001/organize-app
    ports:
      - "127.0.0.1:3000:3000"
    restart: always
  certs:
    image: localhost:5001/organize-certs
    restart: always
    volumes:
      - cert-www:/var/www/certbot/:rw
      - cert-conf:/etc/letsencrypt/:rw
  db:
    environment:
      POSTGRES_PASSWORD: ${ORGANIZE_DATABASE_PASSWORD:?err}
    image: postgres:14.5
    ports:
      - "127.0.0.1:5432:5432"
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    depends_on:
      - app
      - certs
    image: localhost:5001/organize-web
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - cert-www:/var/www/certbot/:ro
      - cert-conf:/etc/nginx/ssl/:ro

volumes:
  cert-conf:
  cert-www:
