services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    command: rails server --binding=0.0.0.0
    depends_on:
      - db
    entrypoint: /usr/src/app/docker-entrypoint.sh
    environment:
      ORGANIZE_DATABASE_PASSWORD: ${ORGANIZE_DATABASE_PASSWORD:?err}
      ORGANIZE_DATABASE_USER: postgres
      ORGANIZE_DATABASE_HOST: db
    image: localhost:5001/organize-app
    ports:
      - "127.0.0.1:3000:3000"
  db:
    environment:
      POSTGRES_PASSWORD: ${ORGANIZE_DATABASE_PASSWORD:?err}
    image: postgres:14.5
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    depends_on:
      - app
    image: localhost:5001/organize-web
    ports:
      - "8080:80"
