services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      RAILS_ENV: development
    volumes:
      - .:/usr/src/app
  certs:
    build:
      context: .
      dockerfile: Dockerfile.certs
    environment:
      SELF_SIGN: true
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
