services:
  app:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    environment:
      RAILS_ENV: development
    volumes:
      - ..:/usr/src/app
  certs:
    build:
      context: ..
      dockerfile: docker/certs/Dockerfile
    environment:
      SELF_SIGN: true
    restart: "no"
  web:
    build:
      context: ..
      dockerfile: docker/web/Dockerfile
